import { 
  Zap,
  Lock,
  Smartphone,
  CreditCard,
  Target,
  BarChart,
  Star,
  Heart,
  Settings,
  User,
  Bell,
  Mail,
  Calendar,
  Clock,
  Map,
  Image,
  Video,
  Music,
  File,
  Folder,
  Home,
  Search,
  Send,
  Share,
  Download,
  Upload,
  Trash,
  Edit,
  Plus,
  Minus,
  Check,
  X,
  Menu,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Link,
  Paperclip,
  Save,
  Printer,
  Camera,
  Mic,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Globe,
  Shield,
  Key,
  Eye,
  EyeOff,
  Code,
  Terminal,
  Server,
  Cloud,
  Database,
  Wifi,
  Bluetooth,
  Battery,
  Power,
  Activity,
  AlertCircle,
  AlertTriangle,
  AlertOctagon,
  Info,
  HelpCircle,
  Dumbbell,
  Flame,
  Trophy,
  Plane,
  Pizza,
  Palette,
  Laptop,
  Users,
  GraduationCap,
  Rocket,
  TrendingUp,
  Sparkles,
  Building,
  BookOpen,
  Coffee,
  Car,
  ShoppingBag,
  Gamepad2,
  Apple,
  Utensils
} from 'lucide-react';

// Map descriptive names to Lucide icons
export const iconMap: { [key: string]: any } = {
  'lightning': Zap,
  'lock': Lock,
  'mobile': Smartphone,
  'card': CreditCard,
  'target': Target,
  'chart': BarChart,
  'star': Star,
  'heart': Heart,
  'settings': Settings,
  'user': User,
  'bell': Bell,
  'mail': Mail,
  'calendar': Calendar,
  'clock': Clock,
  'map': Map,
  'image': Image,
  'video': Video,
  'music': Music,
  'file': File,
  'folder': Folder,
  'home': Home,
  'search': Search,
  'send': Send,
  'share': Share,
  'download': Download,
  'upload': Upload,
  'trash': Trash,
  'edit': Edit,
  'plus': Plus,
  'minus': Minus,
  'check': Check,
  'x': X,
  'menu': Menu,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'external-link': ExternalLink,
  'link': Link,
  'paperclip': Paperclip,
  'save': Save,
  'printer': Printer,
  'camera': Camera,
  'mic': Mic,
  'volume': Volume2,
  'volume-off': VolumeX,
  'play': Play,
  'pause': Pause,
  'square': Square,
  'circle': Circle,
  'triangle': Triangle,
  'hexagon': Hexagon,
  'globe': Globe,
  'shield': Shield,
  'key': Key,
  'eye': Eye,
  'eye-off': EyeOff,
  'code': Code,
  'terminal': Terminal,
  'server': Server,
  'cloud': Cloud,
  'database': Database,
  'wifi': Wifi,
  'bluetooth': Bluetooth,
  'battery': Battery,
  'power': Power,
  'activity': Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'alert-octagon': AlertOctagon,
  'info': Info,
  'help': HelpCircle,
  // New icons for CardGrid
  'dumbbell': Dumbbell,
  'weight': Dumbbell,
  'fitness': Dumbbell,
  'flame': Flame,
  'fire': Flame,
  'burn': Flame,
  'trophy': Trophy,
  'award': Trophy,
  'achievement': Trophy,
  'plane': Plane,
  'travel': Plane,
  'flight': Plane,
  'pizza': Pizza,
  'food': Pizza,
  'eat': Utensils,
  'utensils': Utensils,
  'palette': Palette,
  'art': Palette,
  'design': Palette,
  'laptop': Laptop,
  'computer': Laptop,
  'freelancer': Laptop,
  'users': Users,
  'team': Users,
  'people': Users,
  'graduation': GraduationCap,
  'student': GraduationCap,
  'education': GraduationCap,
  'learn': BookOpen,
  'book': BookOpen,
  'rocket': Rocket,
  'startup': Rocket,
  'entrepreneur': Rocket,
  'trending': TrendingUp,
  'progress': TrendingUp,
  'tracking': TrendingUp,
  'sparkles': Sparkles,
  'motivation': Sparkles,
  'inspiration': Sparkles,
  'zap': Zap,
  'energy': Zap,
  'building': Building,
  'business': Building,
  'corporate': Building,
  'coffee': Coffee,
  'cafe': Coffee,
  'car': Car,
  'transport': Car,
  'shopping': ShoppingBag,
  'bag': ShoppingBag,
  'game': Gamepad2,
  'gaming': Gamepad2,
  'entertainment': Gamepad2,
  'apple': Apple,
  'healthy': Apple,
  'health': Heart,
  // Common aliases
  'photo': Camera,
  'photography': Camera,
  'fashion': ShoppingBag,
  'style': Palette,
  'beginner': User,
  'intermediate': TrendingUp,
  'advanced': Trophy,
  'professional': Building,
  'pro': Trophy
};